on: [push, pull_request]
name: CI

jobs:
  test:
    name: Test
    runs-on: ${{matrix.os.fullname}}
    strategy:
      fail-fast: false
      matrix: 
        os:
          - { prettyname: Windows, fullname: windows-latest }
          - { prettyname: macOS, fullname: macos-latest }
          - { prettyname: Linux, fullname: ubuntu-latest }
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install .NET 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      # FIXME: libavformat is not included in Ubuntu. Let's fix that.
      # https://github.com/ppy/osu-framework/issues/4349
      # Remove this once https://github.com/actions/virtual-environments/issues/3306 has been resolved.
      - name: Install libavformat-dev
        if: ${{matrix.os.fullname == 'ubuntu-latest'}}
        run: |
          sudo apt-get update && \
          sudo apt-get -y install libavformat-dev
          
      - name: Compile
        run: dotnet build -c Debug -warnaserror ScheduleApp.Desktop.slnf
        
      - name: Test
        run: dotnet test $pwd/*.Tests/bin/Debug/*/*.Tests.dll --logger "trx;LogFileName=TestResults-${{matrix.os.prettyname}}.trx"
        shell: pwsh
        
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-results-${{matrix.os.prettyname}}
          path: ${{github.workspace}}/TestResults/TestResults-${{matrix.os.prettyname}}.trx